# -*- coding: utf-8 -*-
"""Gradient Boosting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZCw679kswR4TsXvCbnJA0AIe2QKiWqFh
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt

# Load and prepare data
df = pd.read_csv('/content/processed_ev_data.csv')
target_col   = 'Electric Range (km)'
feature_cols = [c for c in df.columns if c != target_col][:5]
df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors='coerce')
df = df.dropna(subset=feature_cols + [target_col])
X = df[feature_cols].values
y = df[target_col].values

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Train Gradient Boosting
gbr = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)
gbr.fit(X_train, y_train)

# Evaluate
y_pred = gbr.predict(X_test)
r2   = r2_score(y_test, y_pred)
mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print(f"R²:   {r2:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"RMSE: {rmse:.4f}")

# --- Simple Plots ---

# 1) Actual vs Predicted
plt.figure()
plt.scatter(y_test, y_pred, alpha=0.7)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         'k--', lw=1)
plt.xlabel("Actual Electric Range (km)")
plt.ylabel("Predicted Electric Range (km)")
plt.title("Actual vs Predicted")
plt.tight_layout()
plt.show()